updating-workflow

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -35,5 +35,14 @@ jobs:
     - name: Remove Unit Test File
       run: rm unit_test_get_product_list.py
 
+    - name: Check Unit Test Output for Errors
+      run: |
+        if echo "${{ steps.unit-test.outputs.stdout }}" | grep -q "Error"; then
+          echo "Error found in unit test output"
+          exit 1
+        else
+          echo "Unit test passed"
+        fi
+
 #    - name: Generate documentation
 #      run: python generate_doc.py main.py
